language: "perl"
perl:
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"
before_script:
    - cpanm -n Devel::Cover::Report::Coveralls
script:
    perl Makefile.PL && make && cover -test -report coveralls

notifications:
  email:
    on_success: change
    on_failure: always

#matrix:
#  allow_failures:
#    - perl: "5.20"
# perlbrew use 5.20 ERROR: The installation "5.20" is unknown.
